### ISSUE TITLE
[Bug] cumulative layout shift issue

### ISSUE THREAD

**Issue by teoh4770** [LaurierHawkHacks/Landing#279]

**Comment by GabeDiniz** [comment]
Hey @teoh4770, what do you mean by this?

**Comment by teoh4770** [comment]
In short, about section may somehow causes other section of the page to move/shift for a second when it is painted on the screen, thus cumulative layout shift.

**Comment by teoh4770** [comment]
maybe that's one of the reason flickering still happens in our landing page

**Comment by teoh4770** [comment]
why absolute positioning is not recommended: https://github.com/orgs/community/discussions/67845

**Comment by teoh4770** [comment]
The most common causes of a poor CLS are the following:

1. Images without dimensions.

**Comment by teoh4770** [comment]
https://jakearchibald.com/2022/img-aspect-ratio/

**Comment by teoh4770** [comment]
Link: [A more elegant and easier to use solution](https://github.com/WICG/intrinsicsize-attribute/issues/16)

solution:
```CSS
<style>
  img {
    width: 100%;
    height: auto;
    aspect-ratio: attr(width) / attr(height);
  } 
</style>
<img src="hero_image.jpg" alt="" width="500" height="500">
```

Basically, this solution means if the following four conditions are true, 

1. height is set on the element in HTML
2. width is set on the element in HTML
3. height (or width) is set in the CSS — including using percentage values like max-width: 100%;
4. width (or height) is set to auto in the CSS.

then the _**correct image dimensions could be calculated without needing to wait for the images to download**_, and so _**without the need of a content layout shift**_:
